############
##  関数  ##
############
def env_sh(cmd)
  sh "bash -c 'source bin/env.sh && #{cmd}'"
end

def de(args)
  sh %(docker exec #{args})
end

def dc(args)
  sh %(docker compose #{args})
end

# コンテナのステータスを確認
# @param [String | Symbol]
# @return [String]
def get_container_status(*container_names)
  a = container_names.map { |n| `docker inspect --format='{{.State.Status}}' #{n} 2>/dev/null`.chomp }
  a = a.first if a.length == 1
  a
end

############
##  task  ##
############
namespace :cmp do
  desc 'コンテナ立ち上げ'
  task :up do
    dc 'up -d --build'
  end

  desc 'コンテナを落とす'
  task :down do
    dc 'down'
  end
end

namespace :db do
  desc 'dbコンテナに入ってコンソールを開く'
  task :cui do
    unless get_container_status(:postgresdb) == 'running'
      Rake::Task['cmp:up'].invoke
      sleep 0.5
    end
    env_sh %(docker exec -it $POSTGRES_DATABASE psql -U postgres)
  end

  desc 'dbコンテナに入る'
  task :bash do
    Rake::Task['cmp:up'].invoke unless get_container_status(:postgresdb) == 'running'
    env_sh %(docker exec -it $POSTGRES_DATABASE bash)
  end

  desc 'restert'
  task :restart do
    sh 'docker restart POSTGRES8'
  end

  desc 'DB backup'
  task :backup, [:dbname] do |_t, arg|
    env_sh %(docker exec $POSTGRES_DATABASE pg_dump -U postgres #{arg[:dbname]} > ./backup/#{Time.now.strftime('%Y%m%d%H%M%S')}_#{arg[:dbname]}_backup.sql)
  end

  desc 'DB restore'
  task :restore, [:dbname, :path] do |_t, _args|
    de %($POSTGRES_DATABASE pb_restore -U postgres -d #{arg[:dbname]} #{arg[:path]})
  end
end
