FROM ruby:3.2-rc

# RUN apt-get update -qq \
# &&  apt-get install -y nodejs postgresql -clinet npm \
# &&  rm -rf /var/lib/apt/lists/* \
# &&  npm install --global yarn

WORKDIR /project
# COPY Gemfile /rails/Gemfile
# COPY Gemfile.lock /rails/Gemfile.lock
# RUN bundle install
